[package]
name = "converter_rust"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
zip = "0.5.11"
tempdir = "0.3"
serde = { version = "*", features = ["derive"] }
serde_json = "*"