[package]
name = "mania-converter-standalone"
version = "0.6.0-b"
authors = ["Siflorite <monokhrom@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mania-converter = { path = "../../" }