[package]
name = "mania-converter-standalone"
version.workspace = true
authors = ["Siflorite <monokhrom@163.com>"]
edition.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mania-converter = { path = "../../" }
